CREATE DATABASE IF NOT EXISTS gymfit;
USE gymfit;
...

---

## 2) `create_tables.sql`
```sql
-- create_tables.sql
CREATE DATABASE IF NOT EXISTS gymfit;
USE gymfit;

CREATE TABLE MEMBRO (
    MembroID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DataNascimento DATE,
    Telefone VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE TREINADOR (
    TreinadorID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    Especialidade VARCHAR(80),
    Email VARCHAR(100)
);

CREATE TABLE PLANO (
    PlanoID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(80) NOT NULL,
    PrecoMensal DECIMAL(8,2) NOT NULL,
    DuracaoMeses INT NOT NULL
);

CREATE TABLE CLASSE (
    ClasseID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(80) NOT NULL,
    Horario TIME,
    Duracao INT,
    Sala VARCHAR(30)
);

CREATE TABLE TURMA (
    TurmaID INT AUTO_INCREMENT PRIMARY KEY,
    ClasseID INT NOT NULL,
    TreinadorID INT NOT NULL,
    DataInicio DATE,
    FOREIGN KEY (ClasseID) REFERENCES CLASSE(ClasseID),
    FOREIGN KEY (TreinadorID) REFERENCES TREINADOR(TreinadorID)
);

CREATE TABLE EQUIPAMENTO (
    EquipID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(80),
    Tipo VARCHAR(50),
    Status VARCHAR(30)
);

CREATE TABLE MATRICULA (
    MatriculaID INT AUTO_INCREMENT PRIMARY KEY,
    MembroID INT NOT NULL,
    TurmaID INT NOT NULL,
    DataMatricula DATE,
    Status VARCHAR(20),
    FOREIGN KEY (MembroID) REFERENCES MEMBRO(MembroID) ON DELETE CASCADE,
    FOREIGN KEY (TurmaID) REFERENCES TURMA(TurmaID) ON DELETE RESTRICT
);

CREATE TABLE PAGAMENTO (
    PagamentoID INT AUTO_INCREMENT PRIMARY KEY,
    MembroID INT NOT NULL,
    PlanoID INT NOT NULL,
    DataPagamento DATE,
    Valor DECIMAL(8,2),
    FOREIGN KEY (MembroID) REFERENCES MEMBRO(MembroID) ON DELETE CASCADE,
    FOREIGN KEY (PlanoID) REFERENCES PLANO(PlanoID) ON DELETE RESTRICT
);
